wandb_version: 1

cancers:
  desc: null
  value:
  - BRCA
  - LUAD
variable:
  desc: null
  value: DSS
learning_rate:
  desc: null
  value: 0.0001
wd:
  desc: null
  value: 0.1
hidden_size:
  desc: null
  value: 64
architecture:
  desc: null
  value: GCN
nodes:
  desc: null
  value: 11
genes:
  desc: null
  value:
  - C6orf150
  - CCL5
  - CXCL10
  - TMEM173
  - CXCL9
  - CXCL11
  - NFKB1
  - IKBKE
  - IRF3
  - TREX1
  - ATM
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712836579.848602
    t:
      1:
      - 1
      - 41
      - 55
      - 77
      2:
      - 1
      - 41
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.10.13
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
